lib/interfaces/bdd_mocha.js
test/suite/suite_leave_error_breadcrumb.js
test/test_bdd_mocha.js

Add support for passing in Error objects as breadcrumbs

---

doc/bdd_interface.md
doc/interface_api.md
lib/bin/list_suite.js
lib/interfaces/bdd_mocha.js
lib/suite_runner.js
test/suite/suite_slow_set_in_suite.js
test/suite/suite_timeout_get_in_subsuite.js
test/suite/suite_timeout_read_in_suite.js
test/suite/suite_timeout_set_in_subsuite.js
test/suite/suite_timeout_set_in_suite.js
test/test_bdd_mocha.js
test/test_list_suite.js
test/test_suite_runner.js

Allow this.slow and this.timeout in describe blocks

---

lib/reporters/spec.js
test/suite/suite_spec_should_print_to_stdout_by_default.js
test/test_spec.js

Make the Spec reporter print to stdout by default

---

doc/bdd_interface.md
doc/suite_runner_api.md
lib/bin/run_test.js
lib/soft_kill.js
lib/suite_runner.js
test/suite/suite_ensure_after_hook_is_only_run_once.js
test/suite/suite_single_test_that_never_finishes_with_after_hook.js
test/test_run_test.js
test/test_suite_runner.js

Run after hooks even on timeout

---

lib/suite_runner.js
test/test_reporter_api.js

Send finish reporter messages even when the test succeeds and there are retries left

---

lib/reporters/spec.js
lib/reporters/spec_progress.js
test/test_spec_progress.js

Handle test output correctly in the spec reporter

---

lib/suite_runner.js
test/test_suite_runner.js

Better error when not providing files parameter to suite runner

---

doc/suite_runner_api.md
lib/suite_runner.js
test/test_suite_runner.js

Implement invertGrep

---

lib/bin/run_test.js
test/test_reporter_api.js

Always emit "Finished running after hooks" breadcrumb

---

doc/reporter_api.md
lib/reporters/message_tracker.js
test/test_error_detail.js
test/test_message_tracker.js

Otherwise it will always report stuff about after hooks
Closes #95

Don't report breadcrumbs that happened after the test timed out

---

lib/bin/run_test.js
package.json

Apparently it causes issues. See #105

Don't mix co's promises with when promises

---

lib/reporters/teamcity.js
test/test_teamcity.js

Treat timeouts as errors even before finish (hammar)

---

lib/reporters/error_detector.js
lib/suite_runner.js
test/test_error_detector.js

Add details when having failures

---

lib/reporters/teamcity.js
package.json
test/test_teamcity.js

Errors are not reported correctly in the Teamcity reporter when using retries

Not reporting errors correctly in teamcity

---

doc/bdd_interface.md
lib/bin/run_test.js
lib/interfaces/bdd_mocha.js
test/suite/suite_after_each_hook_title.js
test/suite/suite_before_each_hook_title.js
test/suite/suite_test_title.js
test/suite/suite_test_title_in_tests.js
test/test_run_test.js
test/test_suite_runner.js

Want to log the test name in the client log

Add the name of the test in the hook

---

doc/suite_runner_api.md
lib/bin/run_test.js
lib/suite_runner.js
package.json
test/suite/suite_single_test_that_never_finishes_and_spawns_never_ending_processes.js
test/suite/suite_single_test_that_spawns_never_ending_processes.js
test/test_run_test.js
test/test_suite_runner.js

I will add more tests and also some documentation

Kill all subprocesses after run_test has finished

---

lib/bin/run_test.js
package.json
test/test_suite_runner.js
test/util/run_single_test_that_never_finishes.js

Detection and cleanup of tests if overman is killed

---

lib/bin/run_test.js
package.json
test/suite/suite_single_test_uncaught_non_exception.js
test/suite/suite_single_test_uncaught_null.js
test/test_run_test.js

Improve error handling when errors are not Error objects

---

lib/suite_runner.js
test/test_suite_runner.js

suite_runner: fix deprecated debug mode argument

---

test/suite/suite_ensure_after_hook_is_only_run_once.js
test/test_list_suite.js
test/test_promise_util.js
test/test_reporter_api.js
test/test_suite_runner.js

- fix some flawed logic
- migrate from `Promise.defer` to make tests run on up-to-date node

fix broken tests
